# Generated by Django 3.1.2 on 2020-10-23 07:11

from django.db import migrations, models
import django.db.models.deletion
import rest_api.models.post


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ty', models.IntegerField(choices=[(1, 'Unknown'), (2, 'Interest'), (3, 'Face And Skin'), (4, 'Disease'), (5, 'Mental'), (6, 'Eating')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
                ('ty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.habit')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='VideoOwner',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('video_id', models.CharField(max_length=63)),
                ('ad', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.videoowner')),
                ('ty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.habit')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ty', models.IntegerField(choices=[(1, 'Kakaotalk')])),
                ('token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rest_api.models.post.PostImage._save_image_to)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.user'),
        ),
    ]
