# Generated by Django 3.1.2 on 2020-10-23 07:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201023_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittype',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
