# Generated by Django 3.1.2 on 2020-10-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20201023_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhabit',
            unique_together={('user', 'ty')},
        ),
    ]
