# Generated by Django 3.1.2 on 2020-10-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20201023_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
