# Generated by Django 3.1.2 on 2020-10-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habits',
            field=models.ManyToManyField(to='rest_api.Habit'),
        ),
        migrations.DeleteModel(
            name='UserHabit',
        ),
    ]
