# Generated by Django 3.1.2 on 2020-10-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_auto_20201026_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='habits',
            field=models.ManyToManyField(blank=True, to='rest_api.Habit'),
        ),
    ]
