# Generated by Django 3.1.2 on 2020-10-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_postreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('git', models.URLField(max_length=255)),
                ('date_origin', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
